pizza/urls.py
from django.conf.urls import url#librería para configurar las urls que necesitemos en la aplicación
from . import views #importar de las vistas

app_name = 'pizza'#los patrones de url que encontremos, pertenece a pizza
urlpatterns = [
    #/pizza/
    url(r'^$', views.index , name='index'),
    url(r'^([0-9]+)/$', views.pizza_detail , name='detail'),
    url(r'^pizzas/$' , views.PizzasListView.as_view(), name='pizzas'),
    url(r'^pizza/(?P<pk>[0-9]+)/$' , views.PizzaDetailView.as_view(), name='pizza_detail'),

    url(r'^ingredients/$' , views.IngredientListView.as_view(), name='ingres lo que ponemos en la urledientes'),
    url(r'^ingredients/(?P<pk>[0-9]+)/$' , views.IngredientDetailView.as_view(), name='ingredient_detail'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),#primer register, es el nombre de la ruta url que nosotros ponemos
    url(r'^add/$', views.PizzaCreate.as_view(), name='add-pizza'),
    url(r'^update/(?P<pk>[0-9]+)/', views.PizzaUpdate.as_view(), name='update-pizza'),
    url(r'^delete/(?P<pk>[0-9]+)/', views.PizzaDelete.as_view(), name='delete-pizza'),
]

pizzashop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pizza/', include('pizza.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_ROOT)

pizza/models.py
"""from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Pizza(models.Model): #pizza hereda características de Model. 
    name = models.CharField(verbose_name=("Name"), max_length=100) #verbose_name, es el nombre que se da a Name, es interno
    ingredients = models.ManyToManyField("pizza.Ingredient" , verbose_name=("Ingredients"), related_name="pizza")#Ingredient es una tabla
    image = models.CharField(verbose_name=("image"), max_length=500)
    
    def __str__(self): #método igual que el toString de Java, saca el nombre de la pizza
        return self.name#Con este método, en el crud que crea pone el nombre del ingrediente, si no lo ponemos
        #pondría en la aplicación ingrediente object
    def get_absolute_url(self):#coger de la url de entrada el objeto de pizza
         #Devuelve la url de acceso a una instancia de mi nombre de modelo
        return reverse('pizza:pizza_detail', kwargs={'pk' : self.pk })

class Ingredient(models.Model):
    name = models.CharField(verbose_name=("Name"), max_length=100)
    price = models.DecimalField(verbose_name=("Price"), max_digits=6, decimal_places=2)

    def __str__(self): #método igual que el toString de Java, obtiene el nombre del ingrediente
        return self.name + "price " + str(self.price)#Con este método, en el crud que crea pone el nombre del ingrediente, si no lo ponemos
        #pondría en la aplicación ingrediente object

    def get_absolute_url(self):#coger de la url de entrada el objeto de pizza
         #Devuelve la url de acceso a una instancia de mi nombre de modelo
        return reverse('pizza:ingredient_detail', kwargs={'pk' : self.pk })"""

from django.db import models
from decimal import Decimal
from django.core.urlresolvers import reverse

# Create your models here.
class Pizza(models.Model):
    name = models.CharField(verbose_name=("Name"), max_length=100)
    ingredients = models.ManyToManyField("pizza.Ingredient", verbose_name=("Ingredients"), related_name="pizza")
    image = models.FileField(blank=True, null=True)

    @property
    def price(self):
        price = Decimal(0.0)
        for ingredient in self.ingredients.all():
            price += ingredient.price
        return price * Decimal(1.5)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
         """
         Returns the url to access a particular instance of Pizza.
         """
         return reverse('pizza:pizza_detail', kwargs={ 'pk': self.pk })


class Ingredient(models.Model):
    name = models.CharField(verbose_name=("Name"), max_length=100)
    price = models.DecimalField(verbose_name=("Price"), max_digits=6, decimal_places=2)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
         """
         Returns the url to access a particular instance of Ingredient.
         """
         return reverse('pizza:ingredient_detail', kwargs={ 'pk': self.pk })
    

pizza/forms.py
from django.contrib.auth.models import User#importar el modelo de usuario en este formulario
from django import forms #importamos la librería de forms, que nos facilita crear un formulario de html

class UserForm(forms.ModelForm): #creamos user form y heredamos las caracteríaticas de modelForm
    password = forms.CharField(widget=forms.PasswordInput) # usamos la columna password de html, aquí decimos que no muestre los caracteres y que los oculte

    class Meta: #eta es para mapear la información, no tiene
        model = User #coge el modelo de user para tener la información de este modelo
        fields = ['username', 'email', 'password'] #y lo personalizamos con estos tres campos

pizza/views.py
from django.http import HttpResponse
from .models import Pizza,Ingredient
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.views import generic
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import UserForm
from django.views.generic.edit import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse
from django.contrib.auth.mixins import LoginRequiredMixin




# Create your views heredef index(request):
    #conseguimos los numeros de pizza en bbdd
    #num_pizza =Pizza.objects.count()
    #print(num_pizza)
    #construimos la cadena para mostrar
    #micadena="<style>body{background:#000000;color:white}</style><h1>En la pizzeria tenemos: ", num_pizza ,"pizzas</h1>"
    #return HttpResponse(micadena)
    #otra forma de hacerlo :
#def index(request):
    #all_pizzas= Pizza.objects.all()
    #cadena de Html para mostrar en la página
    #html="""
#<html>
    #<head>
    #<style>
#*{  font-family:"ms comic sans";
    #color:white;
    #background-color:black;
    #margin-left:17%;
#}
#h1{
    #margin-left:11%;
#}

    #</style>
    #<title>MI PAGINA DE PIZZAS SUPER CHACHI</title>
    #<h1>Mi lista de pizzas</h1>
    #</head>
    

#"""
    #en este bucle construimos el html
    #for pizza in all_pizzas:
        #construimos url para cada pizza
        #url= '/pizza/' + str(pizza.id) + '/'
        #añadimos url dentro de la cadena de html
        #html += '<a href ="' + url + '">' + pizza.name + '</a><br>'
    #fuera de bucle acordad de la identacion
    #return HttpResponse(html)

#OTRA FORMA DE HACERLO BAJANDO PLANTILLAS


#def index(request):
    #all_pizzas = Pizza.objects.all()
    #template = loader.get_template('pizza/index.html')
    #context ={'all_pizzas': all_pizzas}
    #return HttpResponse(template.render(context,request))

#OTRA FORMA DE HACER EL MÉTODO INDEX MAS OPTIMO

@login_required
def index(request):
    all_pizzas = Pizza.objects.all()
    #numero de visitas a esta vista,contadas como sesion variable
    num_visitas=request.session.get('num_visitas', 0)
    request.session['num_visitas'] = num_visitas+1
    context = {'all_pizzas': all_pizzas,'nombre_curso': 'Curso de Python','num_visitas':num_visitas}
    return render(request, 'pizza/index.html',context)



# esto si pongo otro id no da error, esta mal tiene que salir que no existe esa pizza
# def detail(request,pizza_id):
#     return HttpResponse("<h2>Detalles para la pizza id: " + str(pizza_id) + "</h2>")
# para solucionar el error hacemos otro metodo diferente

#def detail(request,pizza_id):
    #try:
        #pizza=Pizza.objects.get(pk=pizza_id)
    #except Pizza.DoesNotExist:
        #raise Http404("La pizza no existe")
    #return render(request,'pizza/detail.html' ,{'pizza' : pizza})
# hacerlo de otra forma el detail
def pizza_detail(request,pizza_id):
    pizza=get_object_or_404(Pizza, pk=pizza_id)
    return render(request, 'pizza/pizza_detail.html', {'pizza': pizza})
#deberes 
#1- crear album y song
#2. dentro de la carpeta musica creamos un virtual env, y activamos. instalamos django comando startproyect, creamos project de django, y creamos
#la app song. y hacemos todo lo que hemos hecho hoy.

class PizzasListView(LoginRequiredMixin, generic.ListView): #LoginRequiredMixin, es para loguearse al intentar ver la lista de pizzas
    model= Pizza

class PizzaDetailView(LoginRequiredMixin, generic.DetailView):
    model = Pizza

def ingredientes_detail(request,ingredient_id):
    ingredient=get_object_or_404(Ingredient, pk=ingredient_id)
    return render(request, 'pizza/ingredient_detail.html',{'ingredient' : ingredient})

class IngredientListView(generic.ListView):
    model = Ingredient

class IngredientDetailView(generic.DetailView):
    model = Ingredient

#ahora empieza la clase del user form view apra hacer la vista del registro que se hace en forms.py

class UserFormView(View):
   form_class = UserForm
   template_name = 'pizza/register.html'

   #Display blank template
   def get(self, request):
       form = self.form_class(None)
       return render(request, self.template_name, {'form': form})
   
   def post(self, request):
       form = self.form_class(request.POST)
       
       if form.is_valid():
           user = form.save(commit=False)

           #Normalize the data
           email = form.cleaned_data['email']
           username = form.cleaned_data['username']            
           password = form.cleaned_data['password']
           user.set_password(password)
           user.save()

           #returns user object if credentials are correct
           user = authenticate(username= username, password= password)

           if user is not None:
               if user.is_active:
                   login(request, user)
                   return redirect('pizza:index')
           return render(request, self.template_name, {'form': form })

class PizzaCreate(LoginRequiredMixin, CreateView): #estamos creando una clase, pero es un método. Usa el modelo de pizza, pero en formulario, voy a usar todos los campos que hay en el modelo de pizza
    model = Pizza
    fields = '__all__'

class PizzaUpdate(LoginRequiredMixin, UpdateView): 
    model = Pizza
    fields = '__all__'

class PizzaDelete(LoginRequiredMixin, DeleteView): 
    model = Pizza
    def get_success_url(self):
        return reverse('pizza:index')

pizza/templates/pizza/base_generic.html
<DOCTYPE html>
    <html lang="en">
        <head>
            {% block title %}<title>Local Pizza</title>{% endblock %}
        </head>

        <body>
            {% block sidebar %}<!-- insertar navegación por defecto en todas las páginas-->
            {% endblock %}
            {% block content %}
            {% endblock %}
        </body>
    </html>

pizza/templates/pizza/form-template.html
{% for field in form %}
    <div>
        <div>
            <span>{{ field.errors }}</span>
        </div>
        <label for="pizza.name">{{ field.label_tag }}</label>
        <div>{{ field }}</div>
    </div>
{% endfor %}

pizza/templates/pizza/index.html
<h1>{{ nombre_curso }} </h1>
{% if all_pizzas %}
    <ul>
        {% for pizza in all_pizzas %} 
           <!-- <li><a href="/pizza/{{pizza.id}}"> {{pizza.name}}</a></li> -->
           <li><a href="{% url 'pizza:detail' pizza.id%}"> {{pizza.name}}</a></li> 
           
            {% endfor %}
    <p>You have visited this page {{ num_visits }}
        {% if num_visits == 1 %}
        time
        {% else %}
        times
        {% endif %}
    </p>
    </ul>

{% else %}
    <h3> No Pizzas left </h3>
{% endif %}

pizza/templates/pizza/ingredient_detail.html
{% extends "pizza/base_generic.html" %}

{% block content%}
    <h1> Ingrediente: {{ pizza.name }} <img src="{{ pizza.image }}" /></h1>
   
<ul>
    <li>
        {{ ingredient.name}} - {{ ingredient.price}} €
    </li>
</ul>
{% endblock %}

pizza/templates/pizza/ingredient_list.html
{% block content%}
    <h1>Ingredients list</h1>

    {% if ingredient_list %}
    <ul>
        {% for ingredient in ingredient_list %}
        <li>
            <a href="{{ ingredient.get_absolute_url }}">{{ ingredient.name }} </a>   
             </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No hay ingredientes</p>
    {% endif %}
{% endblock%}

pizza/templates/pizza/pizza_detail.html
{% extends "pizza/base_generic.html" %}

{% block content%}
    <h1> Pizza: {{ pizza.name }} <img src="{{ pizza.image.url }}" /></h1>
   
<ul>
    {% for ingredient in pizza.ingredients.all %}
    <li>
        {{ ingredient.name}} - {{ ingredient.price}} €
    </li>
    {% endfor %}
</ul>

<form method="POST" action="{% url 'pizza:delete-pizza' pizza.id %}">
   {% csrf_token %}<input type="submit" value="Delete">
</form>

{% endblock %}

pizza/templates/pizza/pizza_form.html
<!DOCTYPE html>
<html lang="en">
<head>
 
    {% block title %} Add new Pizza {% endblock %}    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Formulario Pizza</title>
</head>
<body>
    {% block content %} 
        <form action="", method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'pizza/form-template.html' %}
            <button type="submit">Submit</button>
        </form>
    {% endblock %}
</body>
</html>

pizza/templates/pizza/pizza_list.html
{% block content%}
    <h1>Pizza list</h1>

    {% if pizza_list %}
    <ul>
        {% for pizza in pizza_list %}
        <li>
            <a href="{{ pizza.get_absolute_url }}">{{ pizza.name }} </a>   
             </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>There are no pizzas left</p>
    {% endif %}
{% endblock%}

pizza/templates/pizza/register.html
<!DOCTYPE html>
<html lang="en">
<head>
   
    {% block title %} Create new account {% endblock %}    
   <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Resgistro</title>
</head>
<body>
    <h3>Register for an Account</h3>
    {% block content %}
        <form action="", method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'pizza/form-template.html' %}
            <button type="submit">Submit</button>
        </form>
    {% endblock %}
</body>
</html>